from app import create_app
from app.auth import auth
from app.models import tipoUsuario, usuario, empleado, proovedor, compra, cliente, pedido, pedidoProducto, compraProducto, producto, tipoProducto, imagenesProducto, db

app = create_app()

app.app_context().push()

db.create_all()

tipoUsuario1 = tipoUsuario('Empleado')
tipoUsuario2 = tipoUsuario('Cliente')
tipoUsuario3 = tipoUsuario('Admin')

usuario1 = usuario('admin', 'userImage_1.png', 'sadsad', 'davids.dvm@gmail.com', 'activo', None, '3')
usuario2 = usuario('santiago', 'userImage_1.png', 'sadsad', 'santiago@gmail.com', 'activo', None, '2')
usuario3 = usuario('juan', 'userImage_1.png', 'sadsad', 'juan@gmail.com', 'activo', None, '2')

empleado1 = empleado('Pepito Gonzales', 'Administrador', '3105628923', 'Activo', 'CE', '25252525', '3')
empleado2 = empleado('Lucia Cardenas', 'Gerente', '3198524759', 'Inactivo', 'CC', '1052628978', '2')
empleado3 = empleado('Santiago Perez', 'Pepo', '3122055247', 'Activo', 'CC', '1525457845', '1')

proovedor1 = proovedor('Flores C SAS', 'Raul', '1052487895', 'CC', 'flores@flores.com', '3189547569')
proovedor2 = proovedor('LasFloresdePedro', 'Pedro', '1030699585', 'CC', 'Pedro@Flowers.com', '3198274715')
proovedor3 = proovedor('Flowers CORP', 'Will', '1030574151', 'CE', 'FlowerC@gmail.com', '3165024147')

compra1 = compra('2021-06-25', '50000', 'Compra de Tulipanes x100,Rosas x800', 'Activo', 1, 2)
compra2 = compra('2021-05-31', '600000', 'Compra orquideas x30, Compra azucenax 300', 'Activo', 2, 1)
compra3 = compra('2020-06-25', '500000', 'Compra Dalia x50, Compra hortensiax100', 'Activo', 3, 1)

cliente1 = cliente('cll 54 bs24-2', '31030445467', 'Ramiro Gonzalez','CC', '5465765489765432', None, '547', '06', '2023', 'Ramiro Gonzalez', '1')
cliente2 = cliente('Crr 28 v67-21', '3143143142', 'Calceto oliente','Paypal', None, 'calcetoRo@gmail.com', None, None, None, 'Calceto', '2')
cliente3 = cliente('Avenida 30 #24-2', '3213213215', 'Porfilo Rojas','CC', '4705234586872343', None, '665', '02', '2025', 'Carlo magno', '3')

pedido1 = pedido('2020-05-02', '50000', 'Pedido de un Boutique Matrimonial', 'Enviado', 1)
pedido2 = pedido('2021-06-03', '90000', 'Pedido de un Boutique cumpleaños', 'Empaquetando', 2)
pedido3 = pedido('2021-04-02', '60004', 'Pedido 41 Rosas Rojas', 'Entregado', 3)

tipProduct1 = tipoProducto ('Unitario')
tipProduct2 = tipoProducto ('Arreglos')
tipProduct3 = tipoProducto ('Boutique')
tipProduct4 = tipoProducto ('Jarron')

imagen1 = imagenesProducto('shop_flower_1.jpg', None, None, None, None)
imagen2 = imagenesProducto('shop_flower_2.jpg', None, None, None, None)
imagen3 = imagenesProducto('shop_flower_3.jpg', None, None, None, None)
imagen4 = imagenesProducto('Flor_Rosa_1.jpg', None, None, None, None)
imagen5 = imagenesProducto('shop_flower_1.jpg', None, None, None, None)
imagen6 = imagenesProducto('lilyIcon_1.jpg', None, None, None, None)
imagen7 = imagenesProducto('flowersIcon_1.jpg', None, None, None, None)
imagen8 = imagenesProducto('Flor_Carnation_1.jpg', None, None, None, None)
imagen9 = imagenesProducto('jarron_flores.jpg', None, None, None, None)
imagen10 = imagenesProducto('jarron_brillo_solar.jpg', None, None, None, None)
imagen11 = imagenesProducto('Luz _de_colores.jpg', None, None, None, None)
imagen12 = imagenesProducto('Rosas_Lirios_Blancos.jpg', None, None, None, None)
imagen13 = imagenesProducto('Bouquet_de_6_girasoles.jpg', None, None, None, None)
imagen14 = imagenesProducto('Arreglo_floral_marqueza.jpg', None, None, None, None)

producto1 = producto(12000, 'Rosa', 500, 'Flores en un jarron Arreglo Tulipanes Flor tipo tulipán de la familia Liliaceae flor con gran aroma, viene con jarrón Características: Tulipanes: Tulipa gesneriana Colores: A elección del usuario', 'Activo', 1, 1)
producto2 = producto(600000, 'Boutique cumpleaños', 600, 'Arreglo floral de cumpleaños','Activo', 2, 2)
producto3 = producto(646545, 'Boutique Matrimonial', 300, 'Arreglo floral Matrimonial','Activo', 3, 3)
producto4 = producto(14000, 'Jarron Brillo Solar', 14, 'Un jarron muy atractivo que a cualquier le encantara','Activo', 4, 4)
producto5 = producto(55000, 'Lavanda', 52, 'Unas flores con un olor increible','Activo', 5, 1)
producto6 = producto(85000, 'Flor Tipo tulipan', 58, 'Un tulipan alegra la vida de cualquiera, puede llegar a ser el regalo perfecto','Activo', 6, 2)
producto7 = producto(120000, 'Ramo de Flores Rojo', 10, 'Un precioso regalo que a cualquier persona le encatara','Activo', 7, 1)
producto8 = producto(58400, 'Rosa tipo Gardenia', 41, 'Las rosas perfectas para decorar el espacio adecuado','Activo', 8, 2)
producto9 = producto(152000, 'Jarron de 36 flores', 54, 'Un jarron increible con las 36 mejores flores de esta especie, sin duda una decoracion perfecta','Activo', 9, 2)
producto10 = producto(89000, 'Jarron Brillo Solar', 12, 'Un jarron de flores lleno de alegria; los mejores girasoles para hacer feliz a cualquiera','Activo', 10, 2)
producto11 = producto(162000, 'Lavanda', 23, 'Un jarron que tan solo de mirarlo ya huele, llena de este agradable perfume natural cualquier espacio de tu casa','Activo', 11, 1)
producto12 = producto(254000, 'Flor Tipo tulipan', 12, 'Un tipo de flor unico en su especie, conquista cualquier alma con esta preciosa flor casi imposible de conseguir','Activo', 12, 4)
producto13 = producto(23000, 'Ramo de Flores Feliz', 11, 'No hay nada como alegrar el dia de cualquiera con este increible ramo de flores','Activo', 13, 4)
producto14 = producto(260000, 'Arreglo de girasoles', 24, 'Un arreglo de girasoles unico e increible para tu hogar','Activo', 14, 3)

pedidoP1 = pedidoProducto(1, 1, 500000, 5)
pedidoP2 = pedidoProducto(2, 2, 1500000, 50)
pedidoP3 = pedidoProducto(3, 3, 2600000, 16)

compraP1 = compraProducto(1, 1, 600000, 1)
compraP2 = compraProducto(2, 2, 60000, 6)
compraP3 = compraProducto(3, 3, 400000, 5)

db.session.add(tipoUsuario1)
db.session.add(tipoUsuario2)
db.session.add(tipoUsuario3)
db.session.add(usuario1)
db.session.add(usuario2)
db.session.add(usuario3)
db.session.add(empleado1)
db.session.add(empleado2)
db.session.add(empleado3)
db.session.add(proovedor1)
db.session.add(proovedor2)
db.session.add(proovedor3)
db.session.add(compra1)
db.session.add(compra2)
db.session.add(compra3)
db.session.add(cliente1)
db.session.add(cliente2)
db.session.add(cliente3)
db.session.add(pedido1)
db.session.add(pedido2)
db.session.add(pedido3)
db.session.add(tipProduct1)
db.session.add(tipProduct2)
db.session.add(tipProduct3)
db.session.add(tipProduct4)
db.session.add(imagen1)
db.session.add(imagen2)
db.session.add(imagen3)
db.session.add(imagen4)
db.session.add(imagen5)
db.session.add(imagen6)
db.session.add(imagen7)
db.session.add(imagen8)
db.session.add(imagen9)
db.session.add(imagen10)
db.session.add(imagen11)
db.session.add(imagen12)
db.session.add(imagen13)
db.session.add(imagen14)
db.session.add(producto1)
db.session.add(producto2)
db.session.add(producto3)
db.session.add(producto4)
db.session.add(producto5)
db.session.add(producto6)
db.session.add(producto7)
db.session.add(producto8)
db.session.add(producto9)
db.session.add(producto10)
db.session.add(producto11)
db.session.add(producto12)
db.session.add(producto13)
db.session.add(producto14)
db.session.add(pedidoP1)
db.session.add(pedidoP2)
db.session.add(pedidoP3)
db.session.add(compraP1)
db.session.add(compraP2)
db.session.add(compraP3)

db.session.commit()
